#!/bin/bash

rm *blurred*
rm resultados.txt
rm blur-effect
rm CMakeCache.txt
rm -rf CMakeFiles
rm -rf images_results
clear


cmake .
make
printf "\n\nOpen MPI Box Blur! \n\n"
# 720p image
printf "\nBlurring 720p.jpg with kernel: 3, machines: 2...\n"
time mpirun -np 2 ./blur-effect 720p.jpg 720p_blurred_kernel_3_machines_2.jpg 3 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 3, machines: 4...\n"
time mpirun -np 4 ./blur-effect 720p.jpg 720p_blurred_kernel_3_machines_4.jpg 3 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 3, machines: 8...\n"
time mpirun -np 8 ./blur-effect 720p.jpg 720p_blurred_kernel_3_machines_8.jpg 3 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 3, machines: 16...\n"
time mpirun -np 16 ./blur-effect 720p.jpg 720p_blurred_kernel_3_machines_16.jpg 3 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 8, machines: 2...\n"
time mpirun -np 2 ./blur-effect 720p.jpg 720p_blurred_kernel_8_machines_2.jpg 8 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 8, machines: 4...\n"
time mpirun -np 4 ./blur-effect 720p.jpg 720p_blurred_kernel_8_machines_4.jpg 8 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 8, machines: 8...\n"
time mpirun -np 8 ./blur-effect 720p.jpg 720p_blurred_kernel_8_machines_8.jpg 8 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 8, machines: 16...\n"
time mpirun -np 16 ./blur-effect 720p.jpg 720p_blurred_kernel_8_machines_16.jpg 8 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 15, machines: 2...\n"
time mpirun -np 2 ./blur-effect 720p.jpg 720p_blurred_kernel_15_machines_2.jpg 15 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 15, machines: 4...\n"
time mpirun -np 4 ./blur-effect 720p.jpg 720p_blurred_kernel_15_machines_4.jpg 15 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 15, machines: 8...\n"
time mpirun -np 8 ./blur-effect 720p.jpg 720p_blurred_kernel_15_machines_8.jpg 15 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 720p.jpg with kernel: 15, machines: 16...\n"
time mpirun -np 16 ./blur-effect 720p.jpg 720p_blurred_kernel_15_machines_16.jpg 15 16 >> resultados.txt
printf "\nBlurred !\n"



# 1080p image
printf "\nBlurring 1080p.jpg with kernel: 3, machines: 2...\n"
time mpirun -np 2 ./blur-effect 1080p.jpg 1080p_blurred_kernel_3_machines_2.jpg 3 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 3, machines: 4...\n"
time mpirun -np 4 ./blur-effect 1080p.jpg 1080p_blurred_kernel_3_machines_4.jpg 3 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 3, machines: 8...\n"
time mpirun -np 8 ./blur-effect 1080p.jpg 1080p_blurred_kernel_3_machines_8.jpg 3 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 3, machines: 16...\n"
time mpirun -np 16 ./blur-effect 1080p.jpg 1080p_blurred_kernel_3_machines_16.jpg 3 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 8, machines: 2...\n"
time mpirun -np 2 ./blur-effect 1080p.jpg 1080p_blurred_kernel_8_machines_2.jpg 8 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 8, machines: 4...\n"
time mpirun -np 4 ./blur-effect 1080p.jpg 1080p_blurred_kernel_8_machines_4.jpg 8 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 8, machines: 8...\n"
time mpirun -np 8 ./blur-effect 1080p.jpg 1080p_blurred_kernel_8_machines_8.jpg 8 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 8, machines: 16...\n"
time mpirun -np 16 ./blur-effect 1080p.jpg 1080p_blurred_kernel_8_machines_16.jpg 8 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 15, machines: 2...\n"
time mpirun -np 2 ./blur-effect 1080p.jpg 1080p_blurred_kernel_15_machines_2.jpg 15 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 15, machines: 4...\n"
time mpirun -np 4 ./blur-effect 1080p.jpg 1080p_blurred_kernel_15_machines_4.jpg 15 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 15, machines: 8...\n"
time mpirun -np 8 ./blur-effect 1080p.jpg 1080p_blurred_kernel_15_machines_8.jpg 15 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 1080p.jpg with kernel: 15, machines: 16...\n"
time mpirun -np 16 ./blur-effect 1080p.jpg 1080p_blurred_kernel_15_machines_16.jpg 15 16 >> resultados.txt
printf "\nBlurred !\n"


# 4K image
printf "\nBlurring 4K.jpeg with kernel: 3, machines: 2...\n"
time mpirun -np 2 ./blur-effect 4K.jpeg 4K_blurred_kernel_3_machines_2.jpeg 3 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 3, machines: 4...\n"
time mpirun -np 4 ./blur-effect 4K.jpeg 4K_blurred_kernel_3_machines_4.jpeg 3 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 3, machines: 8...\n"
time mpirun -np 8 ./blur-effect 4K.jpeg 4K_blurred_kernel_3_machines_8.jpeg 3 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 3, machines: 16...\n"
time mpirun -np 16 ./blur-effect 4K.jpeg 4K_blurred_kernel_3_machines_16.jpeg 3 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 8, machines: 2...\n"
time mpirun -np 2 ./blur-effect 4K.jpeg 4K_blurred_kernel_8_machines_2.jpeg 8 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 8, machines: 4...\n"
time mpirun -np 4 ./blur-effect 4K.jpeg 4K_blurred_kernel_8_machines_4.jpeg 8 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 8, machines: 8...\n"
time mpirun -np 8 ./blur-effect 4K.jpeg 4K_blurred_kernel_8_machines_8.jpeg 8 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 8, machines: 16...\n"
time mpirun -np 16 ./blur-effect 4K.jpeg 4K_blurred_kernel_8_machines_16.jpeg 8 16 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 15, machines: 2...\n"
time mpirun -np 2 ./blur-effect 4K.jpeg 4K_blurred_kernel_15_machines_2.jpeg 15 2 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 15, machines: 4...\n"
time mpirun -np 4 ./blur-effect 4K.jpeg 4K_blurred_kernel_15_machines_4.jpeg 15 4 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 15, machines: 8...\n"
time mpirun -np 8 ./blur-effect 4K.jpeg 4K_blurred_kernel_15_machines_8.jpeg 15 8 >> resultados.txt
printf "\nBlurred !\n"
printf "\nBlurring 4K.jpeg with kernel: 15, machines: 16...\n"
time mpirun -np 16 ./blur-effect 4K.jpeg 4K_blurred_kernel_15_machines_16.jpeg 15 16 >> resultados.txt
printf "\nBlurred !\n"


mkdir images_results
mv *blurred* images_results/


printf "End of all open MPI tests \n\n"
